/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimationsRouteImport } from './routes/animations'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as HttpRouteImport } from './routes/http'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SsrRouteImport } from './routes/ssr'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as RoutingIndexRouteImport } from './routes/routing.index'
import { Route as RoutingStationRouteImport } from './routes/routing.$station'
import { Route as ApiHonoSplatRouteImport } from './routes/api/hono/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsRoute = AnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpRoute = HttpRouteImport.update({
  id: '/http',
  path: '/http',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrRoute = SsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingIndexRoute = RoutingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutingRoute,
} as any)
const RoutingStationRoute = RoutingStationRouteImport.update({
  id: '/$station',
  path: '/$station',
  getParentRoute: () => RoutingRoute,
} as any)
const ApiHonoSplatRoute = ApiHonoSplatRouteImport.update({
  id: '/api/hono/$',
  path: '/api/hono/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/components': typeof ComponentsRoute
  '/forms': typeof FormsRoute
  '/http': typeof HttpRoute
  '/routing': typeof RoutingRouteWithChildren
  '/signals': typeof SignalsRoute
  '/ssr': typeof SsrRoute
  '/templates': typeof TemplatesRoute
  '/testing': typeof TestingRoute
  '/routing/$station': typeof RoutingStationRoute
  '/routing/': typeof RoutingIndexRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/components': typeof ComponentsRoute
  '/forms': typeof FormsRoute
  '/http': typeof HttpRoute
  '/signals': typeof SignalsRoute
  '/ssr': typeof SsrRoute
  '/templates': typeof TemplatesRoute
  '/testing': typeof TestingRoute
  '/routing/$station': typeof RoutingStationRoute
  '/routing': typeof RoutingIndexRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/components': typeof ComponentsRoute
  '/forms': typeof FormsRoute
  '/http': typeof HttpRoute
  '/routing': typeof RoutingRouteWithChildren
  '/signals': typeof SignalsRoute
  '/ssr': typeof SsrRoute
  '/templates': typeof TemplatesRoute
  '/testing': typeof TestingRoute
  '/routing/$station': typeof RoutingStationRoute
  '/routing/': typeof RoutingIndexRoute
  '/api/hono/$': typeof ApiHonoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animations'
    | '/components'
    | '/forms'
    | '/http'
    | '/routing'
    | '/signals'
    | '/ssr'
    | '/templates'
    | '/testing'
    | '/routing/$station'
    | '/routing/'
    | '/api/hono/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animations'
    | '/components'
    | '/forms'
    | '/http'
    | '/signals'
    | '/ssr'
    | '/templates'
    | '/testing'
    | '/routing/$station'
    | '/routing'
    | '/api/hono/$'
  id:
    | '__root__'
    | '/'
    | '/animations'
    | '/components'
    | '/forms'
    | '/http'
    | '/routing'
    | '/signals'
    | '/ssr'
    | '/templates'
    | '/testing'
    | '/routing/$station'
    | '/routing/'
    | '/api/hono/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationsRoute: typeof AnimationsRoute
  ComponentsRoute: typeof ComponentsRoute
  FormsRoute: typeof FormsRoute
  HttpRoute: typeof HttpRoute
  RoutingRoute: typeof RoutingRouteWithChildren
  SignalsRoute: typeof SignalsRoute
  SsrRoute: typeof SsrRoute
  TemplatesRoute: typeof TemplatesRoute
  TestingRoute: typeof TestingRoute
  ApiHonoSplatRoute: typeof ApiHonoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations': {
      id: '/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/http': {
      id: '/http'
      path: '/http'
      fullPath: '/http'
      preLoaderRoute: typeof HttpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr': {
      id: '/ssr'
      path: '/ssr'
      fullPath: '/ssr'
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing/': {
      id: '/routing/'
      path: '/'
      fullPath: '/routing/'
      preLoaderRoute: typeof RoutingIndexRouteImport
      parentRoute: typeof RoutingRoute
    }
    '/routing/$station': {
      id: '/routing/$station'
      path: '/$station'
      fullPath: '/routing/$station'
      preLoaderRoute: typeof RoutingStationRouteImport
      parentRoute: typeof RoutingRoute
    }
    '/api/hono/$': {
      id: '/api/hono/$'
      path: '/api/hono/$'
      fullPath: '/api/hono/$'
      preLoaderRoute: typeof ApiHonoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RoutingRouteChildren {
  RoutingStationRoute: typeof RoutingStationRoute
  RoutingIndexRoute: typeof RoutingIndexRoute
}

const RoutingRouteChildren: RoutingRouteChildren = {
  RoutingStationRoute: RoutingStationRoute,
  RoutingIndexRoute: RoutingIndexRoute,
}

const RoutingRouteWithChildren =
  RoutingRoute._addFileChildren(RoutingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationsRoute: AnimationsRoute,
  ComponentsRoute: ComponentsRoute,
  FormsRoute: FormsRoute,
  HttpRoute: HttpRoute,
  RoutingRoute: RoutingRouteWithChildren,
  SignalsRoute: SignalsRoute,
  SsrRoute: SsrRoute,
  TemplatesRoute: TemplatesRoute,
  TestingRoute: TestingRoute,
  ApiHonoSplatRoute: ApiHonoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
